### ISSUE TITLE
blank screen

### ISSUE THREAD

**Issue by ElusionPDX** [jonassvensson4/jsfour-mdc#10]
after logging in with the password it is just a blank screen but the mouse pointer is there like it thinks its open

**Comment by jnsvns** [comment]
Screenshot? Errors?

**Comment by jnsvns** [comment]
Solved through Discord. Messed up the password.js file

**Comment by jnsvns** [comment]
If you're having the same problem you've done something wrong in the password.js file.

Check for nui://jsfour-mdc/html/assets/js/passwords/js:5 under F8.

(Commenting on this since some others might have the same issue)
