### ISSUE TITLE
On password page if u press tab or scroll it skips it

### ISSUE THREAD

**Issue by AdrineX** [jonassvensson4/jsfour-mdc#11]
and you can use delete buttons without using password.

**Comment by jnsvns** [comment]
I tried to recreate your problem by pressing tab, the scroll wheel or by just scrolling. Nothing let's me through without entering a password. 

Have you modified anything in the script? Have you added the correct lastdigits to the passwords file? Do you get any errors under F8 or in the server console when pressing tab?

And I have no idea which delete button you're talking about. Nothing in the MDC requires a password except when you open it.

**Comment by AdrineX** [comment]
I have made some little changes but, nothing major and no there is no errors. Here is quick video https://streamable.com/q1fbn. I made the computer to open with command /tietokone, because i have almost every button in use. Here is how i could scroll or tab to skip it. At first time i open then panel it works fine, but if i close it and open it again and right after the panel comes up i spam tab and scroll down it skips the password. This was discovered by one of my players.

**Comment by jnsvns** [comment]
I understand what the problem is but I can't recreate it which makes it hard for me to help you. 

My guess is that you've modified something that shoudn't be modified.

**Comment by TheIsNear** [comment]
Hey mate have the same problem here. I've not modified the files. But still I don't know how to get the password.

**Comment by jnsvns** [comment]
> Hey mate have the same problem here. I've not modified the files. But still I don't know how to get the password.

This is not the same issue?..
