### ISSUE TITLE
The password does not work

### ISSUE THREAD

**Issue by AtomicKRG** [jonassvensson4/jsfour-mdc#13]
Ich have installed your jsfour-mdc, jsfour-idcard and jsfour-register scripts. So I have my lastdigits and I created a new password in password.js. But when I open the tablet ingame I get the notification wrong password. Can you show me please how I must link the password with the lastdigits. Thanks for helping.

**Comment by jnsvns** [comment]
Just enter a password and the players lastdigits in the password.js file. There are more information in that file

**Comment by AtomicKRG** [comment]
I have a password look at this shot: http://prntscr.com/mp147y
And then when I open the tablet ingame I enter atomic6749 and I get the error wrong password. What is wrong ?

**Comment by jnsvns** [comment]
atomic is just the password.. Not atomic6749. 

It literraly says PASSWORD WILL BE ATOMIC
