### ISSUE TITLE
Problem with lastdigits

### ISSUE THREAD

**Issue by AtomicKRG** [jonassvensson4/jsfour-mdc#14]
I use your script jsfour-register. The problem is that only admins can see the lastdigits in the database. ASlso I use your script jsfour-mdc but you need the lastdigits for the date of birth but they cannot know because only admins see the lastdigits in the database. How can I edit jsfour-mdc that you not need the lastdigits for the date of birth. Thank you very much for help.

**Comment by jnsvns** [comment]
If you want to remove the lastdigits from the MDC you would have to edit the javascript and the server.lua. 

Or add something that lets the player show the lastdigits (Some id card maybe?).

This is something you have to do by yourself and nothing I will help you with. Good luck

**Comment by AtomicKRG** [comment]
But how can I add the lastdigits to the esx_policejob idcard
