### ISSUE TITLE
After plate run it will say "cant find user date of birth" 

### ISSUE THREAD

**Issue by GeorgKoppel** [jonassvensson4/jsfour-mdc#15]
Hello, i have a issue, I have lastdigits For me its 43. If im searching from Date of birth 43, it gives my information. If searching For my car plate. It shows up like me "Georg Koppe" if klicking on it, It says "Cant find user date of birth" How to fix? Maybe there is way to change date of birth for just Name.

**Comment by jnsvns** [comment]
Wrong use of lastdigits, supposed to be 4 not 2. Solved through Discord.
