### ISSUE TITLE
Pulling DOB does not work. 

### ISSUE THREAD

**Issue by Kolvicht** [jonassvensson4/jsfour-mdc#16]
I'm extremely confused when trying to search a person by their DOB as it is labels yymmdd-xxxx 

I enter that exact format

Ex: 971107-1234 

And it continues to tell me nobody is by that DOB.

**Comment by jnsvns** [comment]
Do you have a user with the lastdigits 1234 in your database?

**Comment by Kolvicht** [comment]
Yes, Bryan fury
DOB 1997-08-11  Last digits 1234

http://prntscr.com/ngxmgd

**Comment by jnsvns** [comment]
Can't really see the column name so I can't tell if it's something wrong in your database.
