### ISSUE TITLE
Error Adding a incident

### ISSUE THREAD

**Issue by SoldatMI** [jonassvensson4/jsfour-mdc#17]
Getting a couple of errors not sure why

https://i.imgur.com/FcDwAtU.png
https://i.imgur.com/dSVbfu8.png

**Comment by jnsvns** [comment]
Looks like you've messed up the passwords.js file

**Comment by SoldatMI** [comment]
I will look into it once I get home, thank you

**Comment by SoldatMI** [comment]
Added the digits correctly I still get the error for the substring but everything seems to work just fine.

**Comment by jnsvns** [comment]
Oh I didn't notice there were 2 different errors. The second one looks a bit weird. Because there are no substring in init.js on row 330 in the original script.
