### ISSUE TITLE
Sevral issues

### ISSUE THREAD

**Issue by MatinHQ** [jonassvensson4/jsfour-mdc#18]
Hello and thanks for your cool script, I have several issues with this script please see the video and you will figure it out: https://youtu.be/hfBCmx5cvUs

**Comment by jnsvns** [comment]
For the vehicle issue: What version of esx_vehicleshop are you using? Does the plate exist in the database?

For the person issue: I can't see that you've any lastdigits in your database. Which the script needs. Please read the installation guide again.

**Comment by MatinHQ** [comment]
Hello again, I tried, to install this script https://github.com/jonassvensson4/jsfour-register but the problem is it's fully Swedish and I can't understand much about this, is that possible to guide me how to install that properly?!

**Comment by MatinHQ** [comment]
https://youtu.be/wu1S1HMiZkA

**Comment by jnsvns** [comment]
I've translated the jsfour-register to english so it should be easy to install it.

You can't change the inspected it will always say Ja. I forgot to change it, you can see the new update in the server.lua. (This is also something I've mentioned in the README)

I still can't see that you're entering the lastdigits when you're searching for a player. That needs to be included! You should be able to search for a player by only using the players lastdigits. Same goes for the wanted part. I can't see your lastdigits in the DOB section.

**Comment by MatinHQ** [comment]
Thanks you are amazing! all of my issues solved and thanks for sharing this script for free <3
