### ISSUE TITLE
SEARCH BY DOB

### ISSUE THREAD

**Issue by ElRocaYT** [jonassvensson4/jsfour-mdc#19]
I was testing de MDC now, and i'm wondering how its possible to my police officers know the ''lastdigits'' from the player they need to look in de MDC. 
Because if i'm not wrong to search anyone by DOB you need to write ''YYYYMMDD-LASTDIGITS''

And another question, there's any way to automatically add ''lastdigits'' to the new players when they create their character or something like that?

Although apart from my doubts a great script both visually and functionally.

**Comment by ElRocaYT** [comment]
Ok, I read that if I use your register instead of identity, the lastidigits are created automaticaly. MY BAD

**Comment by jnsvns** [comment]
Regarding how an officer can know the players lastdigits. Use your imagination? Add it to an ID card that the players can show? Make a text that displays on top of the player? A 3D text infront of the player? I mean you can do anything. It's up to you how you want to show the lastdigits.

To be able to search for someone you only need the lastdigits. The DOB isn't really necessary which means you can call the lastdigits identifications code or something to make it easier for people to understand.
