### ISSUE TITLE
I think it cant connect to my database

### ISSUE THREAD

**Issue by Kuanaxd** [jonassvensson4/jsfour-mdc#2]
when i add the information and go search, we cant see that information. like jsfour-brottsregister.

**Comment by jnsvns** [comment]
Errors?

**Comment by Kuanaxd** [comment]
nothing but i will see again.

**Comment by Kuanaxd** [comment]
i dont have my computer now

**Comment by Kuanaxd** [comment]
JSFOUR-MDC ERROR - WRONG LASTDIGITS IN PASSWORDS.JS COULDNT FIND THE USER WITH LASTDIGITS: 4321
ok i changed and lets see again.

**Comment by Kuanaxd** [comment]
ok worked thx
