### ISSUE TITLE
jquery.js and init.js uncaught syntaxerror and referenceerror

### ISSUE THREAD

**Issue by aGift4u** [jonassvensson4/jsfour-mdc#22]
![1](https://user-images.githubusercontent.com/51796486/61164083-e159c400-a51a-11e9-8578-9558bd7f45d3.PNG)

**Comment by aGift4u** [comment]
Script doens't work at all. I suspect these error codes.

**Comment by jnsvns** [comment]
Looks like jQuery doesn't work. Either re-download the jQuery file or change the src on this <a href="https://github.com/jonassvensson4/jsfour-mdc/blob/master/html/index.html#L213">line</a> to `nui://game/ui/jquery.js`

**Comment by aGift4u** [comment]
Trying right now. Will update.

**Comment by aGift4u** [comment]
It Works!!! Redownloaded jquery files. It was working before, after I changed my vps provider it broke. Thanks Jonas!!!
