### ISSUE TITLE
Add note to car dont work & Wanted shows NO if there is one

### ISSUE THREAD

**Issue by EGUltraTM** [jonassvensson4/jsfour-mdc#23]
Hi,

seems like the add note to an car plate doesnt work.

Andd if a player has wanted entry it shows NO when yousearch for the person with the MDC

**Comment by jnsvns** [comment]
I'm sorry but how am I supposed to help you if that's all you're giving me?..

Errors?

**Comment by EGUltraTM** [comment]
Hi buddy,

i had no errors not from the serverside and also not from the client side in the F8 console. 
thats wierd. I press the Add Note button and nothing happens :D

**Comment by EGUltraTM** [comment]
Can you try the actual resource maybe?
I downloaded only the untouched version added me to the password file and tested it ingame. Of course i injected the sql file etc.

**Comment by jnsvns** [comment]
Of course I've tried the resource? There are currently 327 servers that are using this resource and you're the only one that seems to have issues with it. 

How am I supposed to help you if there are no errors?
