### ISSUE TITLE
Problem with incidents.

### ISSUE THREAD

**Issue by ElGames7** [jonassvensson4/jsfour-mdc#24]
I need help for solve this. 

https://gyazo.com/6f2465e89801b8edbd8d2d300d3f2212

**Comment by jnsvns** [comment]
You're adding someone as wanted and searching for an incident that doesn't exist? What do you want me to help you with? 

Under the open button on the incident tab you have a textarea and a add button. Use that..

**Comment by ElGames7** [comment]
To search or add a user and then search for it. How can it be done?

**Comment by jnsvns** [comment]
I just explained it
You're trying to add a user as WANTED and then you're seaching for an INCIDENT. Those are not the same thing.

**Comment by ElGames7** [comment]
Hmmmm... Okay. Thanks for help me.
