### ISSUE TITLE
How i can login

### ISSUE THREAD

**Issue by Jotteri77** [jonassvensson4/jsfour-mdc#25]
I put password and lastdigits and i try to login not work

**Comment by jnsvns** [comment]
You have to provide more information than that....

Where did you "put" the password and the lastdigits? How did you "put" it there? Screenshot? Pastebin?
Do you get any errors when trying to login?

**Comment by Jotteri77** [comment]
@jonassvensson4 I think i put wrong password and lastdigits here's an example of how I put it. 43917891 so first 4 numbers is password

**Comment by jnsvns** [comment]
That doesn't really tell me much?.. Upload a screenshot

**Comment by Jotteri77** [comment]
![image](https://user-images.githubusercontent.com/43130230/63270390-c0fef100-c2a0-11e9-920f-b45c00121967.png) no any errors or anything

**Comment by Jotteri77** [comment]
@jonassvensson4

**Comment by jnsvns** [comment]
A screenshot of the passwords file.. That's why I told you to either screenshot it or upload it to pastebin.

**Comment by Jotteri77** [comment]
@jonassvensson4 https://pastebin.com/RzKFGRPP

**Comment by jnsvns** [comment]
So the player who has the lastdigits 1116 will have the password 101. And you told me that you're trying to sign in with 43917891?..

**Comment by Jotteri77** [comment]
@jonassvensson4 No its example

**Comment by jnsvns** [comment]
What?..

**Comment by Jotteri77** [comment]
I think i need put password-lastdigits not together

**Comment by jnsvns** [comment]
HOW is the comments not clear enough for you? For real dude..
https://prnt.sc/ounhtr
