### ISSUE TITLE
When i try to make wanted

### ISSUE THREAD

**Issue by Jotteri77** [jonassvensson4/jsfour-mdc#26]
When i try make wanted i get error JSFOUR-MDC ERROR - WRONG LASTDIGITS IN PASSWORDS.JS COULDNT FIND THE USER WITH LASTDIGITS: 4321 im tried lastdigits what is in database and in password.js

**Comment by jnsvns** [comment]
It can't find the user with the lastdigits 4321 in your database.

**Comment by Jotteri77** [comment]
I put lastdigits what in database but dont work

**Comment by Jotteri77** [comment]
When i login in need i put password and lastdigits or only password

**Comment by jnsvns** [comment]
You didn't add the lastdigits to the database according to the error. It can't find anyone with the lastdigits. Check your database again. 

It says password when you log in so use the password, lastdigits is not your password..

**Comment by Jotteri77** [comment]
I have lastdigits in characters and users

**Comment by jnsvns** [comment]
Not according to the error. Upload a screenshot of the lastdigits in your users table

**Comment by Jotteri77** [comment]
![image](https://user-images.githubusercontent.com/43130230/63277646-5c4a9300-c2ae-11e9-9b1e-8815899e31db.png)

**Comment by jnsvns** [comment]
This is getting ridiculous.. Please read the error again

WRONG LASTDIGITS IN PASSWORDS.JS **COULDNT FIND THE USER WITH LASTDIGITS: _4321_**

And you send me a screenshot of the user who has the lastdigits 2865 and not 4321

**Comment by Jotteri77** [comment]
I say i tested lastdigits what in password.js and in database but dont work

**Comment by jnsvns** [comment]
You doesn't seem to understand what I'm saying. You have the lastdigits 4321 in the passwords.js file which it can't find. That's why you're getting that error. That's the error you asked about. Nothing else.

**Comment by Jotteri77** [comment]
![image](https://user-images.githubusercontent.com/43130230/63278497-0676ea80-c2b0-11e9-8789-7e894df82783.png)

**Comment by jnsvns** [comment]
You're right, it was using the wrong lastdigits in the error message.

Could you stop changing stuff around that confuses me? 
So you have the lastidigts 2865 in your passwords.js file AND in your database?

**Comment by Jotteri77** [comment]
But if player want make wanted need make new lastdigitpassword.js or can with admin make with only player lastdigits what in database?

**Comment by jnsvns** [comment]
If you want to make someone wanted you have to know their full date of birth and lastdigits. 

The password.js file is only there to set the passwords for the police officers. This is probably a database issue that's causing this error. Maybe you're using a modified version that doesn't have the correct columns etc..

**Comment by Jotteri77** [comment]
Where i can download normal version?

**Comment by jnsvns** [comment]
What columns do you have in the users table?

**Comment by Jotteri77** [comment]
![image](https://user-images.githubusercontent.com/43130230/63283487-024fca80-c2ba-11e9-825e-0912befaf92f.png)

**Comment by Jotteri77** [comment]
@jonassvensson4

**Comment by jnsvns** [comment]
Looks fine, I don't really know why the query would return emtpy for you.

**Comment by Jotteri77** [comment]
Can u help how i can remove password screen? @jonassvensson4

**Comment by jnsvns** [comment]
Hide it with css and then set the signedInUser variable to someones lastdigits in the javascript. This has nothing to do with the issue..
