### ISSUE TITLE
Nyaste vehliceshop

### ISSUE THREAD

**Issue by Albin323** [jonassvensson4/jsfour-mdc#3]
Den nysate esx_vehicleshop har ändrats mycket, vart ska jag lägga in det som är i optional?

**Comment by jnsvns** [comment]
Du byter ut de filerna som ligger i mappen mot de som redan finns?..

**Comment by jnsvns** [comment]
Du kan förhoppningsvis klicka rund bland mapparna för att hitta filerna.
