### ISSUE TITLE
Optional File - Criminal records

### ISSUE THREAD

**Issue by frenchy77700** [jonassvensson4/jsfour-mdc#5]
I have seen your ypdate four the criminalrecords , am realy happy to see this .
My probleme is i have itegrated the 2 files for the criminal records replacing the main init and server file . All is well execpt i still dont see the criminal records in place or new ones made . Any errors on my side possibly made?

**Comment by jnsvns** [comment]
You don't see the criminal record? Where are you looking?

**Comment by frenchy77700** [comment]
In the mcd computer , i search a player using there id i shows up the page with there information , and on the bottom left there is a spot for criminal records , but even if the player has a record it still doesn't show up on the mcd .

**Comment by jnsvns** [comment]
I just downloaded the files and used the optional files in the jsfour-criminalrecord folder. And it works for me. You've probably installed my criminalrecord the wrong way or something

**Comment by frenchy77700** [comment]
i have just tried reinstalling your criminal records and still nothing , the instalations i have done is replaced the main server and init files instead of replacing the optional files . My question being do i have to replace main files or optional file? seing that the optional file is not taken in account via the ressource file. 
Saying all this i have done a french translation in a couple of the files in all you scripts lol (was hard) do you think that i might of translated a wrong part of a script , a weirdly enough still got it to work? ... and by any chance do you have a discord ? I am realy triing to get this to work i have the whole sytem in place and loving it realy it brings a big must in rp life

**Comment by jnsvns** [comment]
You need to replace the server.lua and init.js located in html/assets/js. 

There's a discord link at my profile
