### ISSUE TITLE
DNA upload

### ISSUE THREAD

**Issue by EGUltraTM** [jonassvensson4/jsfour-mdc#6]
Hi,

seems like the dna upload dosnt work. I use the dna script too.
But when i upload the DNA is unlimited Uploading DNA and nothign happens.
If i close it and try it again it says you have no dna. So it starts but doesnt show anything then

**Comment by jnsvns** [comment]
You must have installed it wrong.

Errors?

**Comment by EGUltraTM** [comment]
No errors.
And the standalone DNA works with upload etc.

**Comment by jnsvns** [comment]
Have you checked the database? I managed to upload it. But I noticed there were no notifications for a successful upload. So it keeps loading even though it's uploaded. 

I've added a notification for this, just download the new init.js

**Comment by EGUltraTM** [comment]
Ah ok thx will check it. 
problem is the DNA exists allready. So i didnt saw if its added or not. 
Waited some message like DNA allready exists or something

**Comment by jnsvns** [comment]
It will say it's uploaded even if the DNA exists.

Let me know if it added it to the database and I'll close this

**Comment by EGUltraTM** [comment]
Yes it works now and is added to the database.
Thank you very much for the fast help :)
