### ISSUE TITLE
How do we get the id of the player

### ISSUE THREAD

**Issue by JakeRyan1** [jonassvensson4/jsfour-mdc#8]
How do we get the personal number of the player i cannot seem to find it.

**Comment by jnsvns** [comment]
Use a script that shows you the ID?..

**Comment by JakeRyan1** [comment]
So the id of the player in the game so if I'm the first one to join the server my id would be 1 i would use 1 or the name of the player's character?

**Comment by jnsvns** [comment]
No? The personal number is the players date of birth and the last digits 900101-1010 That's what ååmmdd-xxxx stands for.

**Comment by JakeRyan1** [comment]
Ahh, I see so to create the new character can I just delete the old esx_idenity and install your js-four register and then clear the old characters table from users and then it should start creating new last digits? if I'm not mistaken.

**Comment by jnsvns** [comment]
Yeah

**Comment by JakeRyan1** [comment]
Okay, thanks sorry for this just thought your stuff is really cool!
