### ISSUE TITLE
model: 11-30-1994

### ISSUE THREAD

**Issue by shyricaus** [jonassvensson4/jsfour-mdc#9]
där jag kan redigera så att det fungerar med datumet för mitt land som är Brasilien, för om det inte är i modellen i Europa inte fånga. datum modell: 11-30-1994 ... typ av identitet identitet.

![image](https://user-images.githubusercontent.com/28937245/47055776-85326100-d18f-11e8-894b-1624b2dd1498.png)

**Comment by shyricaus** [comment]
// Get user info
  function getUser(type, input) {
    if ( type == 'search') {
	  var day = input.substring(0,2);
	  var month = input.substring(3,5);
      var year = '19' + input.substring(8,10);
      var lastdigits = input.substring(7,12);
      var oDOB = day +'-'+ month +'-'+ year
    } else {
      var oDOB       = input.substring(0,10);
      var lastdigits = input.substring(11,15);
    }

**Comment by shyricaus** [comment]
I wanted to ask if it's here to edit and if my edit is right

**Comment by shyricaus** [comment]
![image](https://user-images.githubusercontent.com/28937245/47056886-be210480-d194-11e8-82ba-86d11f2449fd.png)

**Comment by shyricaus** [comment]
and the identity does not have the registration number

**Comment by shyricaus** [comment]
I found it where I think I have to edit more I can not, could you please give me a help, and if there is any other corner to edit for it to work, I would appreciate it if you would leave me an example...

// Efterlys add
  $('#efterlys-submit').click(function() {
    if ($('#efterlys-firstname').val() != '' && $('#efterlys-lastname').val() != '' && $('#efterlys-personnummer').val() != '' && $('#efterlys-crime').val() != '' && $('#efterlys-incident').val() != '') {
      var val = $('#efterlys-personnummer').val();
      var year = '19' + val.substring(0,2);
      var month = val.substring(2,4);
      var day = val.substring(4,6);
      var _lastdigits = val.substring(7,12);
      _dob = year +'-'+ month +'-'+ day +'-'+ _lastdigits

  // Get user info
  function getUser(type, input) {
    if ( type == 'search') {
      var year = '19' + input.substring(0,2);
      var month = input.substring(2,4);
      var day = input.substring(4,6);
      var lastdigits = input.substring(7,12);
      var oDOB = year +'-'+ month +'-'+ day
    } else {
      var oDOB       = input.substring(0,10);
      var lastdigits = input.substring(11,15);
    }

**Comment by jnsvns** [comment]
I don't speak spanish or what ever that was.

**Comment by shyricaus** [comment]
Hi, could you help me?
my jsfour-mdc is not picking up because of my country's date
could you explain to me where I would edit for him to be picking up the date of my country.

the date of my country and how the image above
